version: "3"
services:
  backend:
    build: './backend'
    ports:
      - "10010:10010"
    expose: 
      - "10010"
    volumes: 
      - "./backend/api:/usr/src/app/api"
      - "./backend/config:/usr/src/app/config"
      - "./backend/test:/usr/src/app/test"
    command: swagger project start
  rethinkdb:
    image: "rethinkdb:latest"
    ports:
      - "8080:8080"